/* THIS FILE IS GENERATED BY SETUP: DO NOT EDIT */
#ifndef IMOD_CONFIG_INCLUDED
#define IMOD_CONFIG_INCLUDED
#define VERSION              4615
#define VERSION_NAME "4.6.15"
#define COPYRIGHT_YEARS "1994-2012"
#define LAB_NAME1 "Boulder Laboratory for 3-Dimensional"
#define LAB_NAME2 "Electron Microscopy of Cells"
#define G77__HACK
#define DLLEXPORT_H
#define DLL_IM_EX
#ifdef _MSC_VER
#define strdup _strdup
#endif
#define B3D_LITTLE_ENDIAN
#define WIN32_BIGFILE
#define SWAP_IEEE_FLOATS
#define NO_IMOD_FORK
#define CLIPBOARD_TIMER_HACK 100
#define GLU_CALLBACK void (__stdcall *)(void)
#define CTRL_STRING "Ctrl"
typedef char b3dByte;
typedef unsigned char b3dUByte;
typedef short int b3dInt16;
typedef unsigned short int b3dUInt16;
typedef int b3dInt32;
typedef unsigned int b3dUInt32;
typedef float b3dFloat;

#endif
 
